; Generated by SmartGUI Creater

 Gui, Add, Text, x17 y8 w120 h20, Your Name:
 Gui, Add, Text, x17 y38 w120 h20, Your Year of birth (yyyy):
 Gui, Add, Edit, x157 y8 w100 h20 vName, Name
 Gui, Add, Edit, x157 y38 w100 h20 vYear, yyyy
 Gui, Add, Button, x27 y68 w70 h20, OK
 Gui, Add, Button, x177 y68 w70 h20, Cancel
 Gui, Show, x279 y217 h98 w277, Created By... Someone :D
 Return 

 ButtonCancel:
 GuiClose:
 ExitApp

 ButtonOk:
 Gui, submit
 Age = %A_year% ;%a_year% holds the current year
 Age -= %Year%   ; %year% holds the year submitted by user
 Msgbox, Hey %name%! You're %Age% years old now!
 ExitApp