; Generated by SmartGUI Creater

 Gui, Add, Button, x16 y7 w80 h30, Notepad
 Gui, Show, x366 y234 h49 w114, Generated using SmartGUI Creator
 Return

 ButtonNotepad:
 Run, Notepad
 Return

 GuiClose:
 ExitApp