; Generated by SmartGUI Creater

 Gui, Add, Button, x16 y7 w80 h30, Notepad
 Gui, Show, x366 y234 h49 w114, Generated using SmartGUI Creator
 Return

 ButtonNotepad:
 Run, Notepad
 return ; Return zorgt ervoor dat het progamma blijft draaien
		; Wanneer "return" wordt verwijdert sluit het progamma na het 
		; klikken op de knop.

 GuiClose:
 ExitApp