; Generated by SmartGUI Creater

 Gui, Add, Button, x16 y7 w80 h30, My Windows
 Gui, Show, x366 y234 h49 w114, Generated using SmartGUI Creator
 Return

 ButtonMyWindows:
 msgbox, %A_OSVersion%
 Return

 GuiClose:
 ExitApp